name       : python-aiohttp_socks
version    : 0.2
release    : 1
source     :
    - https://github.com/romis2012/aiohttp-socks/archive/0.2.tar.gz : 5c3b592c6c4546cec6242a061f4b4591cb9da6ec40d05d92a8bf43d62fd2ca91
license    : Apache-2.0
component  : programming.python
summary    : SOCKS proxy connector for aiohttp. SOCKS4(a) and SOCKS5 are supported.
description: |
    SOCKS proxy connector for aiohttp. SOCKS4(a) and SOCKS5 are supported.
builddeps  :
    - python-aiohttp
rundeps    :
    - python-aiohttp
build      : |
    %python3_setup
install    : |
    %python3_install
