name       : python-aiohttp_socks
version    : 0.4.0
release    : 4
source     :
    - https://github.com/romis2012/aiohttp-socks/archive/v0.4.0.tar.gz : fa3918a8400fc9599b7be534a52ad20ce353f94555635d6735bc9eef04645f51
license    : Apache-2.0
component  : programming.python
summary    : SOCKS proxy connector for aiohttp. SOCKS4(a) and SOCKS5 are supported.
description: |
    SOCKS proxy connector for aiohttp. SOCKS4(a) and SOCKS5 are supported.
builddeps  :
    - python-aiohttp
rundeps    :
    - python-aiohttp
build      : |
    %python3_setup
install    : |
    %python3_install
