name       : python-aiohttp_socks
version    : 0.2.2
release    : 3
source     :
    - https://github.com/romis2012/aiohttp-socks/archive/0.2.2.tar.gz : 5558ab02248a9222d785a07fe5d90f081e6e8f9547f8201c84d5c9c5238ddf17
license    : Apache-2.0
component  : programming.python
summary    : SOCKS proxy connector for aiohttp. SOCKS4(a) and SOCKS5 are supported.
description: |
    SOCKS proxy connector for aiohttp. SOCKS4(a) and SOCKS5 are supported.
builddeps  :
    - python-aiohttp
rundeps    :
    - python-aiohttp
build      : |
    %python3_setup
install    : |
    %python3_install
